#!/bin/sh

if [ ! -z "$YCM_CONFIG_GEN_LD_PASSTHROUGH" ]; then
    # Cmake determines compiler properties by compiling a test file, so call clang for this case
    $YCM_CONFIG_GEN_LD_PASSTHROUGH $@

elif [ "$1" = "-v" ]; then
    # Needed to enable clang-specific options for certain build systems (e.g. linux)
    $YCM_CONFIG_GEN_LD_PASSTHROUGH $@

else
    exec true
fi

